import { serve } from "@upstash/workflow/cloudflare";

export default serve<{ text: string }>(async (context) => {
  await context.run("first-step", () => {
    console.log("first step ran");
  });

  await context.run("second-step", () => {
    console.log("second step ran");
  });
});
